### ISSUE TITLE
Scanner crashes

### ISSUE THREAD

**Issue by Brain2k-0005** [danheron/Heron.BlazorQRScanner#1]
![image](https://github.com/user-attachments/assets/d11d22cc-0e4b-4a1a-8084-6f10cf5a15bd)

**Comment by Brain2k-0005** [comment]
<Scanner @ref="ScannerRef" CodeFound="CodeFound" AutoStart="false" AutoStop="true" />
          
        private void CodeFound(string code)
        {
            NavigationManager.NavigateTo($"/login/ssr?token={code}", true);
        }

**Comment by danheron** [comment]
I accidentally used a synchronous JSInterop call.  So it worked on Blazor WASM but not Blazor Server.

I have now fixed this and released a new version.
